spring.application.name=produtos-api


spring.datasource.url=jdbc:h2:mem:produtosdb
spring.datasource.driver-class-name=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

server.port=8080

springdoc.swagger-ui.path=/docs
springdoc.api-docs.path=/api-docs

rate.limit.produtos.requisicoes-por-minuto=5